#服务器配置
server:
  port: 1024
  servlet:
    context-path: /transfer

#spring配置
spring:
  #热加载
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  #数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/analysis?useUnicode=true&characterEncoding=utf-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

#python配置
python:
    executor: D:\software\python\python.exe

#配置返回统一处理类
filter:
  class: transfer.controller.ApiController